[package]
name = "webapp"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
anyhow = "1.0.92"
chrono = { version = "0.4.38", features = ["serde"] }
hostname = "0.4.0"
log = "0.4.22"
mongodb = "3.1.0"
serde = "1.0.214"
tokio = "1.41.0"
simplelog = "0.12.2"
